# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish package to NPM
on:
  release:
    types:
      - created
      - released

defaults:
  run:
    working-directory: ./src

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: echo "github.ref= ${{ github.ref }}, github.run_number= ${{ github.run_number }}."
      - run: echo "github.event_name= ${{ github.event_name }}, github.event.action= ${{ github.event.action }}."
      - run: npm ci
      - run: npm run build
      - run: npm run package

      # - uses: Shopify/upload-to-release@v2.0.0
      #   if: ${{ (github.event_name == 'release') && (github.event.action == 'created') }}
      #   with:
      #     name: logpm.mjs
      #     path: src/publish/logpm.mjs
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
      #     content-type: application/javascript
      # - uses: softprops/action-gh-release@v2.0.5
      #   if: ${{ (github.event_name == 'release') && (github.event.action == 'created') }}
      #   with:
      #     files: src/publish/logpm.mjs

      - run: npm config set '//registry.npmjs.org/:_authToken' "${{secrets.NPM_TOKEN}}"
        if: ${{ (github.event_name == 'release') && (github.event.action == 'released') }}
      - run: npm publish
        if: ${{ (github.event_name == 'release') && (github.event.action == 'released') }}
        working-directory: ./src/publish
